### ISSUE TITLE
No issue, just thank you!

### ISSUE THREAD

**Issue by RandomInternetPreson** [0x23/WaveSimulator2D#1]
This is really interesting code, and I appreciate you sharing it.  I have it up and running, using "pip install cupy-cuda12x" since I have the 12x toolkit installed.

Really fascinating stuff, it's helping me understand questions I've had for some time!

**Comment by 0x23** [comment]
Hi,

Oh thats really nice to hear :) Thank you for sharing your thoughs on the
project and taking the time to write !
Have fun experimenting and learning !
